### ISSUE TITLE
IMPLEMENTARE PUSH E POP

### ISSUE THREAD

**Issue by dime1897** [AndreaAguzzoli/RTES-Project#2]
Pensavo di fare la POP con due parametri: l'elemento da inserire (quindi di tipo T) e la priorità associata all'elemento. Quest'ultima però deve avere un valore di default che è 0 (la priorità massima) perché così se la coda è FIFO si può non specificare la priorità ed il tutto funziona senza problemi. Sei d'accordo? 

Per la PUSH vediamo poi, intanto partirei dalla POP che è anche semplice da testare.

**Comment by AndreaAguzzoli** [comment]
Va benissimo. Avevo in mente lo stesso ragionamento. Inizio a lavorarci subito.

**Comment by AndreaAguzzoli** [comment]
Procedendo all'implementazione, ho notato che la funzione POP non ha bisogno di avere l'elemento come parametro in quanto deve soltanto estrarre l'elemento dalla testa della coda FIFO o dalla testa della coda relativa ad un certo livello di priorità. Per il momento procedo con un solo parametro (la priorità).

**Comment by dime1897** [comment]
@AndreaAguzzoli si hai ragione scusa

**Comment by AndreaAguzzoli** [comment]
Ho terminato di implementare PUSH e POP.
