### ISSUE TITLE
Correggere costruttori & Prova 'provaReliability.cpp'

### ISSUE THREAD

**Issue by AndreaAguzzoli** [AndreaAguzzoli/RTES-Project#3]
Quando hai tempo, **correggi i costruttori** e adattali alle ultime modifiche. Mi sono permesso di fare già alcune modifiche, ma non ho cambiato troppo perchè lo avevi scritto tu. Oltre ai costruttori devi adattare anche la funzione '**setLevels**'. 

Ti segnalo che quando proverai ad eseguire 'provaReliability.cpp' a volte va in dedalock (**correttamente**) perchè la coda è piena e lui non può scartare nessun elemento dentro e non può rinunciare a scrivere quell'elemento (a causa della QoS reliability); quindi, i thread rimangono bloccati in attesa che si liberi un posto che non si libera mai; infatti, nell'esempio che ho creato sono sempre loro che fanno anche le POP(), ma solo una volta ogni 3 esecuzioni, inoltre facendo prima la PUSH() si creano alcune situazioni di deadlock prettamente relative all'esempio in questione; L'output mostra comunque in modo chiaro il corretto funzionamento della logica di gestione dei semafori.

**Comment by dime1897** [comment]
I costruttori li ho corretti ed aggiornati; per la reliability purtroppo per la cavolata che il git pull non è andato come doveva ci devo riguardare nei prossimi giorni. Scusa ancora.
