### ISSUE TITLE
Cambio di priorità per anzianità degli elementi

### ISSUE THREAD

**Issue by AndreaAguzzoli** [AndreaAguzzoli/RTES-Project#4]
Ti lascio solo un'idea che ho avuto su cui ragionare. Avevo pensato ad una possibile soluzione più semplice di quella a cui avevamo pensato. 

Premesso che in c++ esiste il tipo di dato 'time_t' e che un elemento di quel tipo rappresenta il numero di secondi trascorsi dal 01/01/1970 allora:

- Se l'elemento generico <T> possedesse 3 proprietà ('nascita', 'morte' e 'stato'). Attraverso quel tipo di elemento noi possiamo assegnare un valore a 'nascita' e sommandole il timer deciso calcoliamo l'istante di 'morte'. Lo 'stato' indica se è vecchio o no.
- A questo punto potremmo avere un solo thread 'gestore' (o uno per ogni coda) che controlla se gli elementi sono vecchi o no e se sono vecchi li sposta in un'altra coda.
- Segnalo anche il problema che se un elemento è vecchio e va spostato, quella coda potrebbe essere piena e non saprebbe dove metterlo.

**Comment by dime1897** [comment]
Si ho capito cosa intendi ed onestamente mi ispira. Oggi dedico la giornata a guardare quello che hai fatto tu in questi giorni, poi inizio a lavorarci!

**Comment by dime1897** [comment]
Tengo l'issue aperto, ma penso che ci lavoreremo la prima settimana di settembre.
